### ISSUE TITLE
BigInteger conversion of zero-prefix byte array in cf-edhoc

### ISSUE THREAD

**Issue by actyp** [rikard-sics/californium#6]
We recently found an interesting behavior regarding the `BigInteger#toByteArray()` method, which affected the `cf-edhoc#SharedSecretCalculation`.

Specifically, when the input argument `publicKeyX` of methods  `recomputeEcdsa256YFromX` and `recomputeEcdsa384YFromX` had zero-byte prefix, the corresponding `Y value` could not be recomputed.

### Issue

The `BigInteger#toByteArray()` method returns *the minimum number of bytes required to represent the BigInteger*, which means that

```java
byte[] bytes = new byte[] { 0, 1, 2 }
bytes /* [0, 1, 2] */  != new BigInteger(1, bytes).toByteArray() /* [1, 2] */
```

### Specific Case

Focusing on the `SharedSecretCalculation` and specifically the methods `recomputeEcdsa256YFromX` and `recomputeEcdsa384YFromX`:

The input byte array `publicKeyX` should have 32 (resp. 48) byte length.

In the case that has a prefix of `0x00` bytes, the following would hold:

```java
publicKeyX /* 32 bytes */ != new BigInteger(1, publicKeyX).toByteArray() /* < 32 bytes */
```

Now, because the right version of the above byte array was consequently used, the input would have an incorrect length, which is why the method would fail to find an available Y COSE key.

> One quick solution was to pad left the converted array in order to make it have the correct length, although some other systematic check would be more appropriate.

### Related Information on our end

* Our [pull request](https://github.com/protocol-fuzzing/edhoc-fuzzer/pull/92) (in our project) with the related partial solution just for reference

* cf-edhoc commit used: `9bdb7561147a36a2064c2f7968291436b742d2e9`

* Java version used: `17`

* There may also be other usages of the `BigInteger#toByteArray()` method, which we have missed

**Comment by marco-tiloca-sics** [comment]
Thanks a lot for raising this! Now fixed in https://github.com/rikard-sics/californium/commit/d9ed923deb4a4462aaf2bdc9fa3e3b369c8a43d2
